// Code generated by MockGen. DO NOT EDIT.
// Source: ./message_broker.go

// Package testdata is a generated GoMock package.
package testdata

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	entities "github.com/parta4ok/kvs/question/internal/entities"
)

// MockMessageBroker is a mock of MessageBroker interface.
type MockMessageBroker struct {
	ctrl     *gomock.Controller
	recorder *MockMessageBrokerMockRecorder
}

// MockMessageBrokerMockRecorder is the mock recorder for MockMessageBroker.
type MockMessageBrokerMockRecorder struct {
	mock *MockMessageBroker
}

// NewMockMessageBroker creates a new mock instance.
func NewMockMessageBroker(ctrl *gomock.Controller) *MockMessageBroker {
	mock := &MockMessageBroker{ctrl: ctrl}
	mock.recorder = &MockMessageBrokerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageBroker) EXPECT() *MockMessageBrokerMockRecorder {
	return m.recorder
}

// SessionFinishedEvent mocks base method.
func (m *MockMessageBroker) SessionFinishedEvent(ctx context.Context, sessionResult *entities.SessionResult) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SessionFinishedEvent", ctx, sessionResult)
	ret0, _ := ret[0].(error)
	return ret0
}

// SessionFinishedEvent indicates an expected call of SessionFinishedEvent.
func (mr *MockMessageBrokerMockRecorder) SessionFinishedEvent(ctx, sessionResult interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SessionFinishedEvent", reflect.TypeOf((*MockMessageBroker)(nil).SessionFinishedEvent), ctx, sessionResult)
}
