// Code generated by MockGen. DO NOT EDIT.
// Source: ./session_service.go

// Package testdata is a generated GoMock package.
package testdata

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	entities "github.com/parta4ok/kvs/question/internal/entities"
)

// MockSessionService is a mock of SessionService interface.
type MockSessionService struct {
	ctrl     *gomock.Controller
	recorder *MockSessionServiceMockRecorder
}

// MockSessionServiceMockRecorder is the mock recorder for MockSessionService.
type MockSessionServiceMockRecorder struct {
	mock *MockSessionService
}

// NewMockSessionService creates a new mock instance.
func NewMockSessionService(ctrl *gomock.Controller) *MockSessionService {
	mock := &MockSessionService{ctrl: ctrl}
	mock.recorder = &MockSessionServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionService) EXPECT() *MockSessionServiceMockRecorder {
	return m.recorder
}

// CompleteSession mocks base method.
func (m *MockSessionService) CompleteSession(ctx context.Context, sessionID string, answers []*entities.UserAnswer) (*entities.SessionResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteSession", ctx, sessionID, answers)
	ret0, _ := ret[0].(*entities.SessionResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CompleteSession indicates an expected call of CompleteSession.
func (mr *MockSessionServiceMockRecorder) CompleteSession(ctx, sessionID, answers interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteSession", reflect.TypeOf((*MockSessionService)(nil).CompleteSession), ctx, sessionID, answers)
}

// CreateSession mocks base method.
func (m *MockSessionService) CreateSession(ctx context.Context, userID string, topics []string) (string, map[string]entities.Question, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSession", ctx, userID, topics)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(map[string]entities.Question)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateSession indicates an expected call of CreateSession.
func (mr *MockSessionServiceMockRecorder) CreateSession(ctx, userID, topics interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSession", reflect.TypeOf((*MockSessionService)(nil).CreateSession), ctx, userID, topics)
}

// GetAllCompletedUserSessions mocks base method.
func (m *MockSessionService) GetAllCompletedUserSessions(ctx context.Context, userID string) ([]*entities.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllCompletedUserSessions", ctx, userID)
	ret0, _ := ret[0].([]*entities.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllCompletedUserSessions indicates an expected call of GetAllCompletedUserSessions.
func (mr *MockSessionServiceMockRecorder) GetAllCompletedUserSessions(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllCompletedUserSessions", reflect.TypeOf((*MockSessionService)(nil).GetAllCompletedUserSessions), ctx, userID)
}

// ShowTopics mocks base method.
func (m *MockSessionService) ShowTopics(ctx context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShowTopics", ctx)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ShowTopics indicates an expected call of ShowTopics.
func (mr *MockSessionServiceMockRecorder) ShowTopics(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShowTopics", reflect.TypeOf((*MockSessionService)(nil).ShowTopics), ctx)
}
