BEGIN;

INSERT INTO kvs.question_types (name)
VALUES
    ('single selection'),
    ('multi selection'),
    ('true or false');

INSERT INTO kvs.topics (name) VALUES
    ('Базы данных'),
    ('Базовые типы в Go'),
    ('Составные типы в Go')
ON CONFLICT (name) DO NOTHING;

INSERT INTO kvs.questions (question_type_id, topic_id, subject, variants, correct_answers, usage_count) VALUES
    (1, 1, 'Что такое первичный ключ в SQL?', 
     ARRAY['Уникальный идентификатор записи', 'Поле для хранения паролей', 'Индекс для ускорения поиска', 'Ссылка на другую таблицу'], 
     ARRAY['Уникальный идентификатор записи'], 0),
    (1, 1, 'Какой тип JOIN возвращает все строки из обеих таблиц?', 
     ARRAY['INNER JOIN', 'LEFT JOIN', 'RIGHT JOIN', 'FULL OUTER JOIN'], 
     ARRAY['FULL OUTER JOIN'], 0),
    (1, 1, 'Что делает команда COMMIT?', 
     ARRAY['Отменяет транзакцию', 'Сохраняет изменения транзакции', 'Создает новую таблицу', 'Удаляет базу данных'], 
     ARRAY['Сохраняет изменения транзакции'], 0),
    (1, 1, 'Какой тип данных в PostgreSQL может хранить JSON?', 
     ARRAY['JSONB', 'TEXT', 'VARCHAR', 'Все перечисленные'], 
     ARRAY['JSONB'], 0),
    (1, 1, 'Что такое нормализация базы данных?', 
     ARRAY['Процесс уменьшения избыточности данных', 'Увеличение скорости запросов', 'Шифрование данных', 'Сжатие данных'], 
     ARRAY['Процесс уменьшения избыточности данных'], 0),
    (1, 1, 'Какой оператор используется для фильтрации групп в SQL?', 
     ARRAY['WHERE', 'HAVING', 'FILTER', 'GROUP BY'], 
     ARRAY['HAVING'], 0),
    (1, 1, 'Что такое индекс в базе данных?', 
     ARRAY['Структура для ускорения поиска', 'Резервная копия данных', 'Журнал изменений', 'Таблица связей'], 
     ARRAY['Структура для ускорения поиска'], 0),
    (1, 1, 'Какой тип реляционной базы данных не поддерживает SQL?', 
     ARRAY['NoSQL', 'MySQL', 'PostgreSQL', 'SQLite'], 
     ARRAY['NoSQL'], 0),
    (1, 1, 'Что делает команда EXPLAIN?', 
     ARRAY['Удаляет таблицу', 'Показывает план выполнения запроса', 'Экспортирует данные', 'Создает индекс'], 
     ARRAY['Показывает план выполнения запроса'], 0),
    (1, 1, 'Какой тип транзакции обеспечивает наивысший уровень изоляции?', 
     ARRAY['READ UNCOMMITTED', 'READ COMMITTED', 'REPEATABLE READ', 'SERIALIZABLE'], 
     ARRAY['SERIALIZABLE'], 0);

INSERT INTO kvs.questions (question_type_id, topic_id, subject, variants, correct_answers, usage_count) VALUES
    (2, 1, 'Какие из перечисленных являются реляционными БД?', 
     ARRAY['MySQL', 'MongoDB', 'PostgreSQL', 'Redis'], 
     ARRAY['MySQL', 'PostgreSQL'], 0),
    (2, 1, 'Какие операции являются частью ACID?', 
     ARRAY['Atomicity', 'Consistency', 'Isolation', 'Durability'], 
     ARRAY['Atomicity', 'Consistency', 'Isolation', 'Durability'], 0),
    (2, 1, 'Какие из перечисленных являются типами JOIN?', 
     ARRAY['INNER', 'LEFT', 'CROSS', 'LOOP'], 
     ARRAY['INNER', 'LEFT', 'CROSS'], 0),
    (2, 1, 'Какие из перечисленных являются NoSQL БД?', 
     ARRAY['MongoDB', 'Cassandra', 'Redis', 'SQLite'], 
     ARRAY['MongoDB', 'Cassandra', 'Redis'], 0),
    (2, 1, 'Какие из перечисленных являются преимуществами индексов?', 
     ARRAY['Ускорение поиска', 'Уменьшение размера БД', 'Ускорение вставки данных', 'Ускорение запросов с WHERE'], 
     ARRAY['Ускорение поиска', 'Ускорение запросов с WHERE'], 0),
    (2, 1, 'Какие из перечисленных являются уровнями изоляции транзакций?', 
     ARRAY['READ UNCOMMITTED', 'READ COMMITTED', 'REPEATABLE READ', 'SERIALIZABLE'], 
     ARRAY['READ UNCOMMITTED', 'READ COMMITTED', 'REPEATABLE READ', 'SERIALIZABLE'], 0),
    (2, 1, 'Какие из перечисленных являются командами DML?', 
     ARRAY['SELECT', 'INSERT', 'UPDATE', 'CREATE'], 
     ARRAY['SELECT', 'INSERT', 'UPDATE'], 0),
    (2, 1, 'Какие из перечисленных являются типами отношений в БД?', 
     ARRAY['Один к одному', 'Один ко многим', 'Многие ко многим', 'Наследование'], 
     ARRAY['Один к одному', 'Один ко многим', 'Многие ко многим'], 0),
    (2, 1, 'Какие из перечисленных являются проблемами без нормализации?', 
     ARRAY['Избыточность данных', 'Аномалии вставки', 'Аномалии удаления', 'Медленные запросы'], 
     ARRAY['Избыточность данных', 'Аномалии вставки', 'Аномалии удаления'], 0),
    (2, 1, 'Какие из перечисленных являются командами для работы с транзакциями?', 
     ARRAY['BEGIN', 'COMMIT', 'ROLLBACK', 'SAVEPOINT'], 
     ARRAY['BEGIN', 'COMMIT', 'ROLLBACK', 'SAVEPOINT'], 0);

INSERT INTO kvs.questions (question_type_id, topic_id, subject, variants, correct_answers, usage_count) VALUES
    (3, 1, 'Внешний ключ должен всегда ссылаться на первичный ключ другой таблицы.', 
     ARRAY['true', 'false'], 
     ARRAY['true'], 0),
    (3, 1, 'Индексы всегда ускоряют операции вставки данных.', 
     ARRAY['true', 'false'], 
     ARRAY['false'], 0),
    (3, 1, 'Транзакция - это последовательность операций, которая выполняется как единое целое.', 
     ARRAY['true', 'false'], 
     ARRAY['true'], 0),
    (3, 1, 'NoSQL базы данных не поддерживают транзакции.', 
     ARRAY['true', 'false'], 
     ARRAY['false'], 0),
    (3, 1, 'VIEW в SQL - это виртуальная таблица, основанная на результате запроса.', 
     ARRAY['true', 'false'], 
     ARRAY['true'], 0),
    (3, 1, 'Хранимые процедуры выполняются на стороне клиента.', 
     ARRAY['true', 'false'], 
     ARRAY['false'], 0),
    (3, 1, 'TRUNCATE TABLE - это DDL команда.', 
     ARRAY['true', 'false'], 
     ARRAY['true'], 0),
    (3, 1, 'Каскадное удаление автоматически удаляет связанные записи в дочерних таблицах.', 
     ARRAY['true', 'false'], 
     ARRAY['true'], 0),
    (3, 1, 'UNION ALL удаляет дубликаты при объединении результатов.', 
     ARRAY['true', 'false'], 
     ARRAY['false'], 0),
    (3, 1, 'Materialized View хранит результаты запроса на диске.', 
     ARRAY['true', 'false'], 
     ARRAY['true'], 0);

INSERT INTO kvs.questions (question_type_id, topic_id, subject, variants, correct_answers, usage_count) VALUES
    (1, 2, 'Какой тип в Go используется для хранения Unicode символов?', 
     ARRAY['byte', 'rune', 'string', 'int32'], 
     ARRAY['rune'], 0),
    (1, 2, 'Какой нулевой значение для указателей в Go?', 
     ARRAY['0', 'nil', 'null', 'undefined'], 
     ARRAY['nil'], 0),
    (1, 2, 'Какой тип имеет 1.0 по умолчанию в Go?', 
     ARRAY['float32', 'float64', 'int', 'complex64'], 
     ARRAY['float64'], 0),
    (1, 2, 'Какой тип лучше использовать для денежных значений?', 
     ARRAY['float32', 'float64', 'int', 'decimal.Decimal'], 
     ARRAY['decimal.Decimal'], 0),
    (1, 2, 'Какой диапазон значений у типа int8?', 
     ARRAY['0..255', '-128..127', '-32768..32767', '0..65535'], 
     ARRAY['-128..127'], 0),
    (1, 2, 'Какой тип имеет константа 42 в Go?', 
     ARRAY['int', 'int32', 'int64', 'не имеет типа пока не присвоена'], 
     ARRAY['не имеет типа пока не присвоена'], 0),
    (1, 2, 'Какой оператор используется для приведения типов в Go?', 
     ARRAY['cast', 'convert', 'тип(значение)', '(тип)значение'], 
     ARRAY['тип(значение)'], 0),
    (1, 2, 'Какой тип используется для хранения разницы между двумя временными метками?', 
     ARRAY['time.Duration', 'time.Time', 'int64', 'float64'], 
     ARRAY['time.Duration'], 0),
    (1, 2, 'Какой тип имеет результат операции len() для строки?', 
     ARRAY['int', 'int32', 'int64', 'uint'], 
     ARRAY['int'], 0),
    (1, 2, 'Какой тип используется для хранения ошибок в Go?', 
     ARRAY['error', 'string', 'Exception', 'Error'], 
     ARRAY['error'], 0);

INSERT INTO kvs.questions (question_type_id, topic_id, subject, variants, correct_answers, usage_count) VALUES
    (2, 2, 'Какие из перечисленных являются целочисленными типами в Go?', 
     ARRAY['int', 'int32', 'float64', 'uint8'], 
     ARRAY['int', 'int32', 'uint8'], 0),
    (2, 2, 'Какие из перечисленных типов являются alias-ами в Go?', 
     ARRAY['byte', 'rune', 'int8', 'float32'], 
     ARRAY['byte', 'rune'], 0),
    (2, 2, 'Какие из перечисленных являются комплексными типами в Go?', 
     ARRAY['complex64', 'complex128', 'complex32', 'complex'], 
     ARRAY['complex64', 'complex128'], 0),
    (2, 2, 'Какие из перечисленных являются правильными способами объявления переменных?', 
     ARRAY['var x int = 5', 'x := 5', 'x = 5', 'let x = 5'], 
     ARRAY['var x int = 5', 'x := 5'], 0),
    (2, 2, 'Какие из перечисленных типов могут содержать nil?', 
     ARRAY['int', 'string', '[]int', '*int'], 
     ARRAY['[]int', '*int'], 0),
    (2, 2, 'Какие из перечисленных являются типами с плавающей точкой?', 
     ARRAY['float32', 'float64', 'decimal', 'double'], 
     ARRAY['float32', 'float64'], 0),
    (2, 2, 'Какие из перечисленных являются правильными константами в Go?', 
     ARRAY['const x = 42', 'const x int = 42', 'const x := 42', 'const (x = 42)'], 
     ARRAY['const x = 42', 'const x int = 42', 'const (x = 42)'], 0),
    (2, 2, 'Какие из перечисленных операций допустимы для типа rune?', 
     ARRAY['+', '-', '*', '/'], 
     ARRAY['+', '-', '*', '/'], 0),
    (2, 2, 'Какие из перечисленных являются нулевыми значениями для своих типов?', 
     ARRAY['0 для int', '"" для string', 'nil для []int', 'false для bool'], 
     ARRAY['0 для int', '"" для string', 'nil для []int', 'false для bool'], 0),
    (2, 2, 'Какие из перечисленных утверждений верны про iota?', 
     ARRAY['Увеличивается на 1 в каждом const()', 'Может быть сброшена', 'Может использоваться в выражениях', 'Работает вне const()'], 
     ARRAY['Увеличивается на 1 в каждом const()', 'Может использоваться в выражениях'], 0);

-- True or false вопросы для "Базовые типы в Go" (id 51-60)
INSERT INTO kvs.questions (question_type_id, topic_id, subject, variants, correct_answers, usage_count) VALUES
    (3, 2, 'Тип uint может быть отрицательным.', 
     ARRAY['true', 'false'], 
     ARRAY['false'], 0),
    (3, 2, 'byte - это алиас для uint8.', 
     ARRAY['true', 'false'], 
     ARRAY['true'], 0),
    (3, 2, 'Нулевое значение для типа string - это nil.', 
     ARRAY['true', 'false'], 
     ARRAY['false'], 0),
    (3, 2, 'Тип float32 занимает 32 бита памяти.', 
     ARRAY['true', 'false'], 
     ARRAY['true'], 0),
    (3, 2, 'Константы в Go могут быть объявлены без типа.', 
     ARRAY['true', 'false'], 
     ARRAY['true'], 0),
    (3, 2, 'Тип error - это встроенный интерфейс в Go.', 
     ARRAY['true', 'false'], 
     ARRAY['true'], 0),
    (3, 2, 'Оператор := может использоваться для объявления глобальных переменных.', 
     ARRAY['true', 'false'], 
     ARRAY['false'], 0),
    (3, 2, 'Тип rune представляет Unicode код-поинт.', 
     ARRAY['true', 'false'], 
     ARRAY['true'], 0),
    (3, 2, 'В Go есть автоматическое приведение типов между int и float64.', 
     ARRAY['true', 'false'], 
     ARRAY['false'], 0),
    (3, 2, 'Пустая структура struct{} занимает 0 байт памяти.', 
     ARRAY['true', 'false'], 
     ARRAY['true'], 0);

INSERT INTO kvs.questions (question_type_id, topic_id, subject, variants, correct_answers, usage_count) VALUES
    (1, 3, 'Как объявляется массив из 5 целых чисел в Go?', 
     ARRAY['var a [5]int', 'var a []int', 'var a array[5]int', 'var a list[5]int'], 
     ARRAY['var a [5]int'], 0),
    (1, 3, 'Как добавить элемент в срез в Go?', 
     ARRAY['append(slice, elem)', 'slice.add(elem)', 'slice.push(elem)', 'slice[len(slice)] = elem'], 
     ARRAY['append(slice, elem)'], 0),
    (1, 3, 'Какой тип имеет map[string]int?', 
     ARRAY['Массив', 'Срез', 'Отображение', 'Функция'], 
     ARRAY['Отображение'], 0),
    (1, 3, 'Как создать новый канал целых чисел?', 
     ARRAY['chan int', 'new(chan int)', 'make(chan int)', 'channel(int)'], 
     ARRAY['make(chan int)'], 0),
    (1, 3, 'Как получить длину map в Go?', 
     ARRAY['len(map)', 'map.length()', 'map.size()', 'cap(map)'], 
     ARRAY['len(map)'], 0),
    (1, 3, 'Как объявить структуру в Go?', 
     ARRAY['struct { fields }', 'type Name struct { fields }', 'class Name { fields }', 'object Name { fields }'], 
     ARRAY['type Name struct { fields }'], 0),
    (1, 3, 'Какой тип является ссылочным в Go?', 
     ARRAY['Массив', 'Срез', 'Структура', 'Интерфейс'], 
     ARRAY['Срез'], 0),
    (1, 3, 'Как проверить наличие ключа в map?', 
     ARRAY['map.has(key)', 'map.contains(key)', 'value, ok := map[key]', 'map[key] != nil'], 
     ARRAY['value, ok := map[key]'], 0),
    (1, 3, 'Какой тип используется для представления JSON в Go?', 
     ARRAY['json.Object', 'map[string]interface{}', 'struct', 'interface{}'], 
     ARRAY['map[string]interface{}'], 0),
    (1, 3, 'Как создать буферизированный канал?', 
     ARRAY['make(chan int, size)', 'new(chan int, size)', 'chan int(size)', 'bufferedChan(size)'], 
     ARRAY['make(chan int, size)'], 0);

INSERT INTO kvs.questions (question_type_id, topic_id, subject, variants, correct_answers, usage_count) VALUES
    (2, 3, 'Какие из перечисленных являются составными типами в Go?', 
     ARRAY['Массив', 'Срез', 'Структура', 'Интерфейс'], 
     ARRAY['Массив', 'Срез', 'Структура', 'Интерфейс'], 0),
    (2, 3, 'Какие из перечисленных операций допустимы для срезов?', 
     ARRAY['len(slice)', 'cap(slice)', 'append(slice, elem)', 'delete(slice, index)'], 
     ARRAY['len(slice)', 'cap(slice)', 'append(slice, elem)'], 0),
    (2, 3, 'Какие из перечисленных являются правильными способами создания среза?', 
     ARRAY['var s []int', 's := make([]int, 5)', 's := []int{1, 2, 3}', 's := new([]int)'], 
     ARRAY['var s []int', 's := make([]int, 5)', 's := []int{1, 2, 3}'], 0),
    (2, 3, 'Какие из перечисленных утверждений верны для интерфейсов?', 
     ARRAY['Могут содержать методы', 'Могут содержать поля', 'Реализуются неявно', 'Могут быть nil'], 
     ARRAY['Могут содержать методы', 'Реализуются неявно', 'Могут быть nil'], 0),
    (2, 3, 'Какие из перечисленных являются правильными способами итерации по map?', 
     ARRAY['for key, value := range map', 'for key := range map', 'map.forEach(func)', 'for i := 0; i < len(map); i++'], 
     ARRAY['for key, value := range map', 'for key := range map'], 0),
    (2, 3, 'Какие из перечисленных утверждений верны для структур?', 
     ARRAY['Могут содержать методы', 'Могут наследоваться', 'Могут реализовывать интерфейсы', 'Могут быть анонимными'], 
     ARRAY['Могут содержать методы', 'Могут реализовывать интерфейсы', 'Могут быть анонимными'], 0),
    (2, 3, 'Какие из перечисленных операций допустимы для каналов?', 
     ARRAY['<- ch', 'ch <- value', 'close(ch)', 'len(ch)'], 
     ARRAY['<- ch', 'ch <- value', 'close(ch)'], 0),
    (2, 3, 'Какие из перечисленных являются правильными способами работы с JSON?', 
     ARRAY['json.Marshal', 'json.Unmarshal', 'json.Encode', 'json.Decode'], 
     ARRAY['json.Marshal', 'json.Unmarshal'], 0),
    (2, 3, 'Какие из перечисленных утверждений верны для срезов?', 
     ARRAY['Имеют длину и емкость', 'Могут расти динамически', 'Являются value-типами', 'Всегда инициализированы'], 
     ARRAY['Имеют длину и емкость', 'Могут расти динамически'], 0),
    (2, 3, 'Какие из перечисленных являются правильными способами создания map?', 
     ARRAY['var m map[string]int', 'm := make(map[string]int)', 'm := map[string]int{}', 'm := new(map[string]int)'], 
     ARRAY['m := make(map[string]int)', 'm := map[string]int{}'], 0);

INSERT INTO kvs.questions (question_type_id, topic_id, subject, variants, correct_answers, usage_count) VALUES
    (3, 3, 'Срезы в Go всегда инициализированы.', 
     ARRAY['true', 'false'], 
     ARRAY['false'], 0),
    (3, 3, 'Массивы в Go передаются по значению.', 
     ARRAY['true', 'false'], 
     ARRAY['true'], 0),
    (3, 3, 'Интерфейсный тип может быть nil.', 
     ARRAY['true', 'false'], 
     ARRAY['true'], 0),
    (3, 3, 'Структуры в Go поддерживают наследование.', 
     ARRAY['true', 'false'], 
     ARRAY['false'], 0),
    (3, 3, 'Каналы в Go являются thread-safe.', 
     ARRAY['true', 'false'], 
     ARRAY['true'], 0),
    (3, 3, 'Map в Go можно сравнивать с помощью оператора ==.', 
     ARRAY['true', 'false'], 
     ARRAY['false'], 0),
    (3, 3, 'Пустой интерфейс interface{} может содержать любое значение.', 
     ARRAY['true', 'false'], 
     ARRAY['true'], 0),
    (3, 3, 'Срезы в Go всегда создаются с помощью make().', 
     ARRAY['true', 'false'], 
     ARRAY['false'], 0),
    (3, 3, 'Функции в Go являются first-class объектами.', 
     ARRAY['true', 'false'], 
     ARRAY['true'], 0),
    (3, 3, 'Тип error - это особый тип в Go, не являющийся интерфейсом.', 
     ARRAY['true', 'false'], 
     ARRAY['false'], 0);

END;