services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: knowledge
    ports:
      - "5432:5432"
    networks:
      - service_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d knowledge" ]
      interval: 10s
      timeout: 5s
      retries: 5
    profiles:
      - services
      - l1
      - l2
  kvs_app:
    container_name: knowledge_validation_system_app
    build:
      context: .
      dockerfile: knowledge_checker/dockerfile
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - service_network
    profiles:
      - services
      - l1
      - l2


networks:
  service_network:
    driver: bridge
