services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: knowledge
    ports:
      - "5432:5432"
    networks:
      - service_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d knowledge" ]
      interval: 10s
      timeout: 5s
      retries: 5
    profiles:
      - services

networks:
  service_network:
    driver: bridge
