version: "3"

tasks:
  lint:
    cmds:
      - golangci-lint run -c ./.golangci.yml ./...
  postgres:up:
    desc: Run Postgres service
    cmds:
      - docker-compose up -d postgres

  postgres:restart:
    desc: Restart Postgres service
    cmds:
      - docker-compose restart postgres

  postgres:stop:
    desc: Stop Postgres service
    cmds:
      - docker-compose stop postgres

  postgres:migrate:up:
    desc: Apply all up migrations to Postgres
    cmds:
      - migrate -path knowledge_checker/deploy/migrations/postgres -database "postgresql://postgres:password@localhost:5432/knowledge?sslmode=disable" up

  postgres:migrate:down:
    desc: Revert all migrations (down) on Postgres
    cmds:
      - migrate -path knowledge_checker/deploy/migrations/postgres -database "postgresql://postgres:password@localhost:5432/knowledge?sslmode=disable" down

  services:up:
    desc: Run all services containers with force rebuild and clean start
    cmds:
      - docker-compose --profile services down -v
      - docker-compose --profile services up -d --build --force-recreate

  services:down:
    desc: Stop and remove all services containers with volumes
    cmds:
      - docker-compose --profile services down -v

  l1_test:
    desc: Run L1 test with container infrastructure
    cmds:
      - task: postgres:up
      - cmd: sleep 1
      - task: postgres:migrate:up
      - export $(grep -v '^#' .env | xargs) && go test -v -tags=KVS_TEST_L1 ./...
      - task: postgres:stop
  l2_test:
    desc: Run L2 integration tests with service and container infrastructure
    cmds:
      - task: postgres:up
      - cmd: sleep 2
      - task: postgres:migrate:up
      - cmd: KVS_CONFIG_PATH=./deployment/knowledge_checker.yaml go run ./knowledge_checker/cmd/knowledge_checker_service/main.go &
      - cmd: sleep 5
      - cmd: go test -v -tags=KVS_TEST_L2 ./knowledge_checker/test/l2/...
      - cmd: pkill -f "go run.*knowledge_checker_service"
      - task: postgres:stop
  swag_gen:
    desc: Generate swagger specification (JSON only)
    cmds:
      - swag init -g ./knowledge_checker/internal/port/http/public/doc.go --outputTypes json --parseDependency true --parseInternal
      - cp docs/swagger.json knowledge_checker/api/http/public/swagger.json
  run_service_local:
    desc: Run service locally with local config
    cmds:
      - KVS_CONFIG_PATH=./deployment/knowledge_checker.yaml go run ./knowledge_checker/cmd/knowledge_checker_service/main.go
