FROM golang:1.24-alpine AS builder

WORKDIR /app

RUN go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.1.6
COPY ./.golangci.yml ./

COPY go.mod go.sum ./

RUN go mod download

COPY . .


WORKDIR /app/knowledge_checker

RUN go test ./...
RUN golangci-lint run -c /app/.golangci.yml


RUN go build -o ./cmd/knowledge_checker_service/kvs ./cmd/knowledge_checker_service/main.go

FROM alpine:latest AS executer

WORKDIR /app

RUN mkdir -p /app
WORKDIR /app

COPY --from=builder /app/knowledge_checker/cmd/knowledge_checker_service/kvs .
COPY --from=builder /app/deployment/knowledge_checker.yaml .

CMD ["./kvs", "--config=knowledge_checker.yaml"]