// Code generated by MockGen. DO NOT EDIT.
// Source: command_factory.go

// Package testdata is a generated GoMock package.
package testdata

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	entities "github.com/parta4ok/kvs/auth/internal/entities"
)

// MockCommandFactory is a mock of CommandFactory interface.
type MockCommandFactory struct {
	ctrl     *gomock.Controller
	recorder *MockCommandFactoryMockRecorder
}

// MockCommandFactoryMockRecorder is the mock recorder for MockCommandFactory.
type MockCommandFactoryMockRecorder struct {
	mock *MockCommandFactory
}

// NewMockCommandFactory creates a new mock instance.
func NewMockCommandFactory(ctrl *gomock.Controller) *MockCommandFactory {
	mock := &MockCommandFactory{ctrl: ctrl}
	mock.recorder = &MockCommandFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommandFactory) EXPECT() *MockCommandFactoryMockRecorder {
	return m.recorder
}

// NewAddGroupCommand mocks base method.
func (m *MockCommandFactory) NewAddGroupCommand(title, linkedID string) entities.Command {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewAddGroupCommand", title, linkedID)
	ret0, _ := ret[0].(entities.Command)
	return ret0
}

// NewAddGroupCommand indicates an expected call of NewAddGroupCommand.
func (mr *MockCommandFactoryMockRecorder) NewAddGroupCommand(title, linkedID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewAddGroupCommand", reflect.TypeOf((*MockCommandFactory)(nil).NewAddGroupCommand), title, linkedID)
}

// NewAddUserCommand mocks base method.
func (m *MockCommandFactory) NewAddUserCommand(user *entities.User) entities.Command {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewAddUserCommand", user)
	ret0, _ := ret[0].(entities.Command)
	return ret0
}

// NewAddUserCommand indicates an expected call of NewAddUserCommand.
func (mr *MockCommandFactoryMockRecorder) NewAddUserCommand(user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewAddUserCommand", reflect.TypeOf((*MockCommandFactory)(nil).NewAddUserCommand), user)
}

// NewDeleteUserCommand mocks base method.
func (m *MockCommandFactory) NewDeleteUserCommand(userID string) entities.Command {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewDeleteUserCommand", userID)
	ret0, _ := ret[0].(entities.Command)
	return ret0
}

// NewDeleteUserCommand indicates an expected call of NewDeleteUserCommand.
func (mr *MockCommandFactoryMockRecorder) NewDeleteUserCommand(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewDeleteUserCommand", reflect.TypeOf((*MockCommandFactory)(nil).NewDeleteUserCommand), userID)
}

// NewGetGroupTitleByIDCommand mocks base method.
func (m *MockCommandFactory) NewGetGroupTitleByIDCommand(groupID string) entities.Command {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewGetGroupTitleByIDCommand", groupID)
	ret0, _ := ret[0].(entities.Command)
	return ret0
}

// NewGetGroupTitleByIDCommand indicates an expected call of NewGetGroupTitleByIDCommand.
func (mr *MockCommandFactoryMockRecorder) NewGetGroupTitleByIDCommand(groupID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewGetGroupTitleByIDCommand", reflect.TypeOf((*MockCommandFactory)(nil).NewGetGroupTitleByIDCommand), groupID)
}

// NewGetLinkedUsersCommand mocks base method.
func (m *MockCommandFactory) NewGetLinkedUsersCommand(userID string) entities.Command {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewGetLinkedUsersCommand", userID)
	ret0, _ := ret[0].(entities.Command)
	return ret0
}

// NewGetLinkedUsersCommand indicates an expected call of NewGetLinkedUsersCommand.
func (mr *MockCommandFactoryMockRecorder) NewGetLinkedUsersCommand(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewGetLinkedUsersCommand", reflect.TypeOf((*MockCommandFactory)(nil).NewGetLinkedUsersCommand), userID)
}

// NewGetMentorGroupsCommand mocks base method.
func (m *MockCommandFactory) NewGetMentorGroupsCommand(mentorID string) entities.Command {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewGetMentorGroupsCommand", mentorID)
	ret0, _ := ret[0].(entities.Command)
	return ret0
}

// NewGetMentorGroupsCommand indicates an expected call of NewGetMentorGroupsCommand.
func (mr *MockCommandFactoryMockRecorder) NewGetMentorGroupsCommand(mentorID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewGetMentorGroupsCommand", reflect.TypeOf((*MockCommandFactory)(nil).NewGetMentorGroupsCommand), mentorID)
}

// NewGetUserByIDCommand mocks base method.
func (m *MockCommandFactory) NewGetUserByIDCommand(userID string) entities.Command {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewGetUserByIDCommand", userID)
	ret0, _ := ret[0].(entities.Command)
	return ret0
}

// NewGetUserByIDCommand indicates an expected call of NewGetUserByIDCommand.
func (mr *MockCommandFactoryMockRecorder) NewGetUserByIDCommand(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewGetUserByIDCommand", reflect.TypeOf((*MockCommandFactory)(nil).NewGetUserByIDCommand), userID)
}

// NewIntrospectedCommand mocks base method.
func (m *MockCommandFactory) NewIntrospectedCommand(cjwt string) entities.Command {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewIntrospectedCommand", cjwt)
	ret0, _ := ret[0].(entities.Command)
	return ret0
}

// NewIntrospectedCommand indicates an expected call of NewIntrospectedCommand.
func (mr *MockCommandFactoryMockRecorder) NewIntrospectedCommand(cjwt interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewIntrospectedCommand", reflect.TypeOf((*MockCommandFactory)(nil).NewIntrospectedCommand), cjwt)
}

// NewSignInCommand mocks base method.
func (m *MockCommandFactory) NewSignInCommand(userName, password string) entities.Command {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewSignInCommand", userName, password)
	ret0, _ := ret[0].(entities.Command)
	return ret0
}

// NewSignInCommand indicates an expected call of NewSignInCommand.
func (mr *MockCommandFactoryMockRecorder) NewSignInCommand(userName, password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewSignInCommand", reflect.TypeOf((*MockCommandFactory)(nil).NewSignInCommand), userName, password)
}

// NewUpdateUserCommand mocks base method.
func (m *MockCommandFactory) NewUpdateUserCommand(user *entities.User) entities.Command {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewUpdateUserCommand", user)
	ret0, _ := ret[0].(entities.Command)
	return ret0
}

// NewUpdateUserCommand indicates an expected call of NewUpdateUserCommand.
func (mr *MockCommandFactoryMockRecorder) NewUpdateUserCommand(user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewUpdateUserCommand", reflect.TypeOf((*MockCommandFactory)(nil).NewUpdateUserCommand), user)
}
