// Code generated by MockGen. DO NOT EDIT.
// Source: ./question_client.go

// Package testdata is a generated GoMock package.
package testdata

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	entities "github.com/parta4ok/kvs/reporting/internal/entities"
)

// MockQuestionClient is a mock of QuestionClient interface.
type MockQuestionClient struct {
	ctrl     *gomock.Controller
	recorder *MockQuestionClientMockRecorder
}

// MockQuestionClientMockRecorder is the mock recorder for MockQuestionClient.
type MockQuestionClientMockRecorder struct {
	mock *MockQuestionClient
}

// NewMockQuestionClient creates a new mock instance.
func NewMockQuestionClient(ctrl *gomock.Controller) *MockQuestionClient {
	mock := &MockQuestionClient{ctrl: ctrl}
	mock.recorder = &MockQuestionClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuestionClient) EXPECT() *MockQuestionClientMockRecorder {
	return m.recorder
}

// GetPassedStudentsTopics mocks base method.
func (m *MockQuestionClient) GetPassedStudentsTopics(ctx context.Context, students []string) (map[string][]entities.Topic, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPassedStudentsTopics", ctx, students)
	ret0, _ := ret[0].(map[string][]entities.Topic)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPassedStudentsTopics indicates an expected call of GetPassedStudentsTopics.
func (mr *MockQuestionClientMockRecorder) GetPassedStudentsTopics(ctx, students interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPassedStudentsTopics", reflect.TypeOf((*MockQuestionClient)(nil).GetPassedStudentsTopics), ctx, students)
}
