FROM golang:1.25-alpine AS builder

WORKDIR /app

RUN go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.1.6
COPY ./.golangci.yml ./

COPY go.mod go.sum ./

RUN go mod download

COPY . .


WORKDIR /app/notificationhub

RUN go test ./...
RUN golangci-lint run -c /app/.golangci.yml


RUN go build -o ./cmd/app/notificationhub ./cmd/app/main.go

FROM alpine:latest AS executer

WORKDIR /app

RUN mkdir -p /app
WORKDIR /app

COPY --from=builder /app/notificationhub/cmd/app/notificationhub .
COPY --from=builder /app/deployment/notificationhub.yaml .

CMD ["./notificationhub", "--config=notificationhub.yaml"]
