// Code generated by MockGen. DO NOT EDIT.
// Source: storage.go

// Package testdata is a generated GoMock package.
package testdata

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	entities "github.com/parta4ok/kvs/auth/internal/entities"
)

// MockStorage is a mock of Storage interface.
type MockStorage struct {
	ctrl     *gomock.Controller
	recorder *MockStorageMockRecorder
}

// MockStorageMockRecorder is the mock recorder for MockStorage.
type MockStorageMockRecorder struct {
	mock *MockStorage
}

// NewMockStorage creates a new mock instance.
func NewMockStorage(ctrl *gomock.Controller) *MockStorage {
	mock := &MockStorage{ctrl: ctrl}
	mock.recorder = &MockStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorage) EXPECT() *MockStorageMockRecorder {
	return m.recorder
}

// AddGroup mocks base method.
func (m *MockStorage) AddGroup(ctx context.Context, gid, title, mentorID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddGroup", ctx, gid, title, mentorID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddGroup indicates an expected call of AddGroup.
func (mr *MockStorageMockRecorder) AddGroup(ctx, gid, title, mentorID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddGroup", reflect.TypeOf((*MockStorage)(nil).AddGroup), ctx, gid, title, mentorID)
}

// GetAllGroups mocks base method.
func (m *MockStorage) GetAllGroups(ctx context.Context) ([]*entities.Group, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllGroups", ctx)
	ret0, _ := ret[0].([]*entities.Group)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllGroups indicates an expected call of GetAllGroups.
func (mr *MockStorageMockRecorder) GetAllGroups(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllGroups", reflect.TypeOf((*MockStorage)(nil).GetAllGroups), ctx)
}

// GetAllUsers mocks base method.
func (m *MockStorage) GetAllUsers(ctx context.Context) ([]*entities.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllUsers", ctx)
	ret0, _ := ret[0].([]*entities.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllUsers indicates an expected call of GetAllUsers.
func (mr *MockStorageMockRecorder) GetAllUsers(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllUsers", reflect.TypeOf((*MockStorage)(nil).GetAllUsers), ctx)
}

// GetGroupTitleByID mocks base method.
func (m *MockStorage) GetGroupTitleByID(ctx context.Context, groupID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGroupTitleByID", ctx, groupID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGroupTitleByID indicates an expected call of GetGroupTitleByID.
func (mr *MockStorageMockRecorder) GetGroupTitleByID(ctx, groupID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGroupTitleByID", reflect.TypeOf((*MockStorage)(nil).GetGroupTitleByID), ctx, groupID)
}

// GetLinkedUsers mocks base method.
func (m *MockStorage) GetLinkedUsers(ctx context.Context, userID string) (*entities.LinkedUsers, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLinkedUsers", ctx, userID)
	ret0, _ := ret[0].(*entities.LinkedUsers)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLinkedUsers indicates an expected call of GetLinkedUsers.
func (mr *MockStorageMockRecorder) GetLinkedUsers(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLinkedUsers", reflect.TypeOf((*MockStorage)(nil).GetLinkedUsers), ctx, userID)
}

// GetMentorGroups mocks base method.
func (m *MockStorage) GetMentorGroups(ctx context.Context, mentorID string) ([]*entities.Group, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMentorGroups", ctx, mentorID)
	ret0, _ := ret[0].([]*entities.Group)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMentorGroups indicates an expected call of GetMentorGroups.
func (mr *MockStorageMockRecorder) GetMentorGroups(ctx, mentorID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMentorGroups", reflect.TypeOf((*MockStorage)(nil).GetMentorGroups), ctx, mentorID)
}

// GetUserByID mocks base method.
func (m *MockStorage) GetUserByID(ctx context.Context, userID string) (*entities.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", ctx, userID)
	ret0, _ := ret[0].(*entities.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockStorageMockRecorder) GetUserByID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockStorage)(nil).GetUserByID), ctx, userID)
}

// GetUserByUsername mocks base method.
func (m *MockStorage) GetUserByUsername(ctx context.Context, userName string) (*entities.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByUsername", ctx, userName)
	ret0, _ := ret[0].(*entities.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByUsername indicates an expected call of GetUserByUsername.
func (mr *MockStorageMockRecorder) GetUserByUsername(ctx, userName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByUsername", reflect.TypeOf((*MockStorage)(nil).GetUserByUsername), ctx, userName)
}

// RemoveUser mocks base method.
func (m *MockStorage) RemoveUser(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveUser", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveUser indicates an expected call of RemoveUser.
func (mr *MockStorageMockRecorder) RemoveUser(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveUser", reflect.TypeOf((*MockStorage)(nil).RemoveUser), ctx, userID)
}

// StoreDynamicRegistrations mocks base method.
func (m *MockStorage) StoreDynamicRegistrations(ctx context.Context, reg *entities.DynamicRegistrationParameters) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreDynamicRegistrations", ctx, reg)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreDynamicRegistrations indicates an expected call of StoreDynamicRegistrations.
func (mr *MockStorageMockRecorder) StoreDynamicRegistrations(ctx, reg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreDynamicRegistrations", reflect.TypeOf((*MockStorage)(nil).StoreDynamicRegistrations), ctx, reg)
}

// StoreUser mocks base method.
func (m *MockStorage) StoreUser(ctx context.Context, user *entities.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreUser", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreUser indicates an expected call of StoreUser.
func (mr *MockStorageMockRecorder) StoreUser(ctx, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreUser", reflect.TypeOf((*MockStorage)(nil).StoreUser), ctx, user)
}

// UpdateUser mocks base method.
func (m *MockStorage) UpdateUser(ctx context.Context, user *entities.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUser", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *MockStorageMockRecorder) UpdateUser(ctx, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*MockStorage)(nil).UpdateUser), ctx, user)
}
