// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package testdata is a generated GoMock package.
package testdata

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	entities "github.com/parta4ok/kvs/reporting/internal/entities"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// DeliverySessionResult mocks base method.
func (m *MockService) DeliverySessionResult(ctx context.Context, session *entities.SessionResult) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeliverySessionResult", ctx, session)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeliverySessionResult indicates an expected call of DeliverySessionResult.
func (mr *MockServiceMockRecorder) DeliverySessionResult(ctx, session interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeliverySessionResult", reflect.TypeOf((*MockService)(nil).DeliverySessionResult), ctx, session)
}

// GetPassedTopicsByGroups mocks base method.
func (m *MockService) GetPassedTopicsByGroups(ctx context.Context, mentorID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPassedTopicsByGroups", ctx, mentorID)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetPassedTopicsByGroups indicates an expected call of GetPassedTopicsByGroups.
func (mr *MockServiceMockRecorder) GetPassedTopicsByGroups(ctx, mentorID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPassedTopicsByGroups", reflect.TypeOf((*MockService)(nil).GetPassedTopicsByGroups), ctx, mentorID)
}
