// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package testdata is a generated GoMock package.
package testdata

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	entities "github.com/parta4ok/kvs/question/internal/entities"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// GetPassedStudentsTopics mocks base method.
func (m *MockService) GetPassedStudentsTopics(ctx context.Context, students []string) (map[string][]*entities.Topic, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPassedStudentsTopics", ctx, students)
	ret0, _ := ret[0].(map[string][]*entities.Topic)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPassedStudentsTopics indicates an expected call of GetPassedStudentsTopics.
func (mr *MockServiceMockRecorder) GetPassedStudentsTopics(ctx, students interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPassedStudentsTopics", reflect.TypeOf((*MockService)(nil).GetPassedStudentsTopics), ctx, students)
}
