// Code generated by MockGen. DO NOT EDIT.
// Source: event_storage.go

// Package testdata is a generated GoMock package.
package testdata

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	event "github.com/parta4ok/kvs/question/internal/entities/event"
)

// MockEventStorage is a mock of EventStorage interface.
type MockEventStorage struct {
	ctrl     *gomock.Controller
	recorder *MockEventStorageMockRecorder
}

// MockEventStorageMockRecorder is the mock recorder for MockEventStorage.
type MockEventStorageMockRecorder struct {
	mock *MockEventStorage
}

// NewMockEventStorage creates a new mock instance.
func NewMockEventStorage(ctrl *gomock.Controller) *MockEventStorage {
	mock := &MockEventStorage{ctrl: ctrl}
	mock.recorder = &MockEventStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventStorage) EXPECT() *MockEventStorageMockRecorder {
	return m.recorder
}

// FlushPublishedEvents mocks base method.
func (m *MockEventStorage) FlushPublishedEvents(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FlushPublishedEvents", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// FlushPublishedEvents indicates an expected call of FlushPublishedEvents.
func (mr *MockEventStorageMockRecorder) FlushPublishedEvents(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FlushPublishedEvents", reflect.TypeOf((*MockEventStorage)(nil).FlushPublishedEvents), ctx)
}

// GetUnpublishedEvents mocks base method.
func (m *MockEventStorage) GetUnpublishedEvents(ctx context.Context) ([]event.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUnpublishedEvents", ctx)
	ret0, _ := ret[0].([]event.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUnpublishedEvents indicates an expected call of GetUnpublishedEvents.
func (mr *MockEventStorageMockRecorder) GetUnpublishedEvents(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUnpublishedEvents", reflect.TypeOf((*MockEventStorage)(nil).GetUnpublishedEvents), ctx)
}

// MarkEventAsPublished mocks base method.
func (m *MockEventStorage) MarkEventAsPublished(ctx context.Context, id int, fn func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkEventAsPublished", ctx, id, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkEventAsPublished indicates an expected call of MarkEventAsPublished.
func (mr *MockEventStorageMockRecorder) MarkEventAsPublished(ctx, id, fn interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkEventAsPublished", reflect.TypeOf((*MockEventStorage)(nil).MarkEventAsPublished), ctx, id, fn)
}
