// Code generated by MockGen. DO NOT EDIT.
// Source: ./report.go

// Package testdata is a generated GoMock package.
package testdata

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	entities "github.com/parta4ok/kvs/reporting/internal/entities"
)

// MockReport is a mock of Report interface.
type MockReport struct {
	ctrl     *gomock.Controller
	recorder *MockReportMockRecorder
}

// MockReportMockRecorder is the mock recorder for MockReport.
type MockReportMockRecorder struct {
	mock *MockReport
}

// NewMockReport creates a new mock instance.
func NewMockReport(ctrl *gomock.Controller) *MockReport {
	mock := &MockReport{ctrl: ctrl}
	mock.recorder = &MockReportMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReport) EXPECT() *MockReportMockRecorder {
	return m.recorder
}

// GetReport mocks base method.
func (m *MockReport) GetReport() interface{} {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReport")
	ret0, _ := ret[0].(interface{})
	return ret0
}

// GetReport indicates an expected call of GetReport.
func (mr *MockReportMockRecorder) GetReport() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReport", reflect.TypeOf((*MockReport)(nil).GetReport))
}

// Kind mocks base method.
func (m *MockReport) Kind() entities.MessageType {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Kind")
	ret0, _ := ret[0].(entities.MessageType)
	return ret0
}

// Kind indicates an expected call of Kind.
func (mr *MockReportMockRecorder) Kind() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Kind", reflect.TypeOf((*MockReport)(nil).Kind))
}

// SetMessageType mocks base method.
func (m *MockReport) SetMessageType() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetMessageType")
}

// SetMessageType indicates an expected call of SetMessageType.
func (mr *MockReportMockRecorder) SetMessageType() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMessageType", reflect.TypeOf((*MockReport)(nil).SetMessageType))
}
