// Code generated by MockGen. DO NOT EDIT.
// Source: ./representer.go

// Package testdata is a generated GoMock package.
package testdata

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	entities "github.com/parta4ok/kvs/reporting/internal/entities"
)

// MockRepresenter is a mock of Representer interface.
type MockRepresenter struct {
	ctrl     *gomock.Controller
	recorder *MockRepresenterMockRecorder
}

// MockRepresenterMockRecorder is the mock recorder for MockRepresenter.
type MockRepresenterMockRecorder struct {
	mock *MockRepresenter
}

// NewMockRepresenter creates a new mock instance.
func NewMockRepresenter(ctrl *gomock.Controller) *MockRepresenter {
	mock := &MockRepresenter{ctrl: ctrl}
	mock.recorder = &MockRepresenterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepresenter) EXPECT() *MockRepresenterMockRecorder {
	return m.recorder
}

// CovertToFormat mocks base method.
func (m *MockRepresenter) CovertToFormat(format entities.Format, report entities.Report) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CovertToFormat", format, report)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CovertToFormat indicates an expected call of CovertToFormat.
func (mr *MockRepresenterMockRecorder) CovertToFormat(format, report interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CovertToFormat", reflect.TypeOf((*MockRepresenter)(nil).CovertToFormat), format, report)
}
