syntax = "proto3";

package auth;

option go_package = "api/grpc/v1;authv1";

service AuthService {
  rpc Introspect (IntrospectRequest) returns (IntrospectResponse);
  rpc GetLinkedUsers(LinkedID) returns (LinkedUsersResponse);
}

message IntrospectRequest {
  string token = 1;
}

message IntrospectResponse {
    UserClaims claims = 1;
    Error error = 2;
}

message UserClaims {
  string username = 1;
  string issuer = 2;
  repeated string audience = 3;
  string subject = 4;
  repeated string rights = 5;
}

message Error {
  string message = 1;
}

message LinkedID {
	string LinkedID = 1;
}

message LinkedUsersResponse {
	UserInfo Recipient = 1;
  UserInfo Student = 2;
	Error error = 3;
}

message UserInfo {
  string id = 1;
  string username = 2;
  string fullname = 3;
  repeated string rights = 4;
  map<string, string> contacts = 5;
  string group_id = 6;
}
