// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/grpc/v1/auth.proto

package authv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IntrospectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntrospectRequest) Reset() {
	*x = IntrospectRequest{}
	mi := &file_api_grpc_v1_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntrospectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntrospectRequest) ProtoMessage() {}

func (x *IntrospectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntrospectRequest.ProtoReflect.Descriptor instead.
func (*IntrospectRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_auth_proto_rawDescGZIP(), []int{0}
}

func (x *IntrospectRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type IntrospectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Claims        *UserClaims            `protobuf:"bytes,1,opt,name=claims,proto3" json:"claims,omitempty"`
	Error         *Error                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntrospectResponse) Reset() {
	*x = IntrospectResponse{}
	mi := &file_api_grpc_v1_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntrospectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntrospectResponse) ProtoMessage() {}

func (x *IntrospectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntrospectResponse.ProtoReflect.Descriptor instead.
func (*IntrospectResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_auth_proto_rawDescGZIP(), []int{1}
}

func (x *IntrospectResponse) GetClaims() *UserClaims {
	if x != nil {
		return x.Claims
	}
	return nil
}

func (x *IntrospectResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type UserClaims struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Issuer        string                 `protobuf:"bytes,2,opt,name=issuer,proto3" json:"issuer,omitempty"`
	Audience      []string               `protobuf:"bytes,3,rep,name=audience,proto3" json:"audience,omitempty"`
	Subject       string                 `protobuf:"bytes,4,opt,name=subject,proto3" json:"subject,omitempty"`
	Rights        []string               `protobuf:"bytes,5,rep,name=rights,proto3" json:"rights,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserClaims) Reset() {
	*x = UserClaims{}
	mi := &file_api_grpc_v1_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserClaims) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserClaims) ProtoMessage() {}

func (x *UserClaims) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserClaims.ProtoReflect.Descriptor instead.
func (*UserClaims) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_auth_proto_rawDescGZIP(), []int{2}
}

func (x *UserClaims) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserClaims) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *UserClaims) GetAudience() []string {
	if x != nil {
		return x.Audience
	}
	return nil
}

func (x *UserClaims) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *UserClaims) GetRights() []string {
	if x != nil {
		return x.Rights
	}
	return nil
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_api_grpc_v1_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_auth_proto_rawDescGZIP(), []int{3}
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type LinkedID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LinkedID      string                 `protobuf:"bytes,1,opt,name=LinkedID,proto3" json:"LinkedID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinkedID) Reset() {
	*x = LinkedID{}
	mi := &file_api_grpc_v1_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkedID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkedID) ProtoMessage() {}

func (x *LinkedID) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkedID.ProtoReflect.Descriptor instead.
func (*LinkedID) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_auth_proto_rawDescGZIP(), []int{4}
}

func (x *LinkedID) GetLinkedID() string {
	if x != nil {
		return x.LinkedID
	}
	return ""
}

type MentorID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MentorID      string                 `protobuf:"bytes,1,opt,name=MentorID,proto3" json:"MentorID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MentorID) Reset() {
	*x = MentorID{}
	mi := &file_api_grpc_v1_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MentorID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MentorID) ProtoMessage() {}

func (x *MentorID) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MentorID.ProtoReflect.Descriptor instead.
func (*MentorID) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_auth_proto_rawDescGZIP(), []int{5}
}

func (x *MentorID) GetMentorID() string {
	if x != nil {
		return x.MentorID
	}
	return ""
}

type UserID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        string                 `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserID) Reset() {
	*x = UserID{}
	mi := &file_api_grpc_v1_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserID) ProtoMessage() {}

func (x *UserID) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserID.ProtoReflect.Descriptor instead.
func (*UserID) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_auth_proto_rawDescGZIP(), []int{6}
}

func (x *UserID) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

type GroupID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupID       string                 `protobuf:"bytes,1,opt,name=GroupID,proto3" json:"GroupID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupID) Reset() {
	*x = GroupID{}
	mi := &file_api_grpc_v1_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupID) ProtoMessage() {}

func (x *GroupID) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupID.ProtoReflect.Descriptor instead.
func (*GroupID) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_auth_proto_rawDescGZIP(), []int{7}
}

func (x *GroupID) GetGroupID() string {
	if x != nil {
		return x.GroupID
	}
	return ""
}

type LinkedUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Recipient     *UserInfo              `protobuf:"bytes,1,opt,name=Recipient,proto3" json:"Recipient,omitempty"`
	Student       *UserInfo              `protobuf:"bytes,2,opt,name=Student,proto3" json:"Student,omitempty"`
	Error         *Error                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinkedUsersResponse) Reset() {
	*x = LinkedUsersResponse{}
	mi := &file_api_grpc_v1_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkedUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkedUsersResponse) ProtoMessage() {}

func (x *LinkedUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkedUsersResponse.ProtoReflect.Descriptor instead.
func (*LinkedUsersResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_auth_proto_rawDescGZIP(), []int{8}
}

func (x *LinkedUsersResponse) GetRecipient() *UserInfo {
	if x != nil {
		return x.Recipient
	}
	return nil
}

func (x *LinkedUsersResponse) GetStudent() *UserInfo {
	if x != nil {
		return x.Student
	}
	return nil
}

func (x *LinkedUsersResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type UserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Fullname      string                 `protobuf:"bytes,3,opt,name=fullname,proto3" json:"fullname,omitempty"`
	Rights        []string               `protobuf:"bytes,4,rep,name=rights,proto3" json:"rights,omitempty"`
	Contacts      map[string]string      `protobuf:"bytes,5,rep,name=contacts,proto3" json:"contacts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	GroupId       string                 `protobuf:"bytes,6,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_api_grpc_v1_auth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_auth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_auth_proto_rawDescGZIP(), []int{9}
}

func (x *UserInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserInfo) GetFullname() string {
	if x != nil {
		return x.Fullname
	}
	return ""
}

func (x *UserInfo) GetRights() []string {
	if x != nil {
		return x.Rights
	}
	return nil
}

func (x *UserInfo) GetContacts() map[string]string {
	if x != nil {
		return x.Contacts
	}
	return nil
}

func (x *UserInfo) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

type Student struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Fullname      string                 `protobuf:"bytes,3,opt,name=fullname,proto3" json:"fullname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Student) Reset() {
	*x = Student{}
	mi := &file_api_grpc_v1_auth_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Student) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Student) ProtoMessage() {}

func (x *Student) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_auth_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Student.ProtoReflect.Descriptor instead.
func (*Student) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_auth_proto_rawDescGZIP(), []int{10}
}

func (x *Student) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Student) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Student) GetFullname() string {
	if x != nil {
		return x.Fullname
	}
	return ""
}

type Group struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Students      []*Student             `protobuf:"bytes,3,rep,name=students,proto3" json:"students,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Group) Reset() {
	*x = Group{}
	mi := &file_api_grpc_v1_auth_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Group) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Group) ProtoMessage() {}

func (x *Group) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_auth_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Group.ProtoReflect.Descriptor instead.
func (*Group) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_auth_proto_rawDescGZIP(), []int{11}
}

func (x *Group) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Group) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Group) GetStudents() []*Student {
	if x != nil {
		return x.Students
	}
	return nil
}

type GroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         *Group                 `protobuf:"bytes,1,opt,name=Group,proto3" json:"Group,omitempty"`
	Error         *Error                 `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupResponse) Reset() {
	*x = GroupResponse{}
	mi := &file_api_grpc_v1_auth_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupResponse) ProtoMessage() {}

func (x *GroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_auth_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupResponse.ProtoReflect.Descriptor instead.
func (*GroupResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_auth_proto_rawDescGZIP(), []int{12}
}

func (x *GroupResponse) GetGroup() *Group {
	if x != nil {
		return x.Group
	}
	return nil
}

func (x *GroupResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type GroupsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Groups        []*Group               `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	Error         *Error                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupsResponse) Reset() {
	*x = GroupsResponse{}
	mi := &file_api_grpc_v1_auth_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupsResponse) ProtoMessage() {}

func (x *GroupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_auth_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupsResponse.ProtoReflect.Descriptor instead.
func (*GroupsResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_auth_proto_rawDescGZIP(), []int{13}
}

func (x *GroupsResponse) GetGroups() []*Group {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *GroupsResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type UserInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *UserInfo              `protobuf:"bytes,1,opt,name=User,proto3" json:"User,omitempty"`
	Error         *Error                 `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfoResponse) Reset() {
	*x = UserInfoResponse{}
	mi := &file_api_grpc_v1_auth_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfoResponse) ProtoMessage() {}

func (x *UserInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_auth_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfoResponse.ProtoReflect.Descriptor instead.
func (*UserInfoResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_auth_proto_rawDescGZIP(), []int{14}
}

func (x *UserInfoResponse) GetUser() *UserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *UserInfoResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_api_grpc_v1_auth_proto protoreflect.FileDescriptor

const file_api_grpc_v1_auth_proto_rawDesc = "" +
	"\n" +
	"\x16api/grpc/v1/auth.proto\x12\x04auth\")\n" +
	"\x11IntrospectRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"a\n" +
	"\x12IntrospectResponse\x12(\n" +
	"\x06claims\x18\x01 \x01(\v2\x10.auth.UserClaimsR\x06claims\x12!\n" +
	"\x05error\x18\x02 \x01(\v2\v.auth.ErrorR\x05error\"\x8e\x01\n" +
	"\n" +
	"UserClaims\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x16\n" +
	"\x06issuer\x18\x02 \x01(\tR\x06issuer\x12\x1a\n" +
	"\baudience\x18\x03 \x03(\tR\baudience\x12\x18\n" +
	"\asubject\x18\x04 \x01(\tR\asubject\x12\x16\n" +
	"\x06rights\x18\x05 \x03(\tR\x06rights\"!\n" +
	"\x05Error\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"&\n" +
	"\bLinkedID\x12\x1a\n" +
	"\bLinkedID\x18\x01 \x01(\tR\bLinkedID\"&\n" +
	"\bMentorID\x12\x1a\n" +
	"\bMentorID\x18\x01 \x01(\tR\bMentorID\" \n" +
	"\x06UserID\x12\x16\n" +
	"\x06UserID\x18\x01 \x01(\tR\x06UserID\"#\n" +
	"\aGroupID\x12\x18\n" +
	"\aGroupID\x18\x01 \x01(\tR\aGroupID\"\x90\x01\n" +
	"\x13LinkedUsersResponse\x12,\n" +
	"\tRecipient\x18\x01 \x01(\v2\x0e.auth.UserInfoR\tRecipient\x12(\n" +
	"\aStudent\x18\x02 \x01(\v2\x0e.auth.UserInfoR\aStudent\x12!\n" +
	"\x05error\x18\x03 \x01(\v2\v.auth.ErrorR\x05error\"\xfc\x01\n" +
	"\bUserInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bfullname\x18\x03 \x01(\tR\bfullname\x12\x16\n" +
	"\x06rights\x18\x04 \x03(\tR\x06rights\x128\n" +
	"\bcontacts\x18\x05 \x03(\v2\x1c.auth.UserInfo.ContactsEntryR\bcontacts\x12\x19\n" +
	"\bgroup_id\x18\x06 \x01(\tR\agroupId\x1a;\n" +
	"\rContactsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"I\n" +
	"\aStudent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bfullname\x18\x03 \x01(\tR\bfullname\"V\n" +
	"\x05Group\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12)\n" +
	"\bstudents\x18\x03 \x03(\v2\r.auth.StudentR\bstudents\"U\n" +
	"\rGroupResponse\x12!\n" +
	"\x05Group\x18\x01 \x01(\v2\v.auth.GroupR\x05Group\x12!\n" +
	"\x05Error\x18\x02 \x01(\v2\v.auth.ErrorR\x05Error\"X\n" +
	"\x0eGroupsResponse\x12#\n" +
	"\x06groups\x18\x01 \x03(\v2\v.auth.GroupR\x06groups\x12!\n" +
	"\x05error\x18\x02 \x01(\v2\v.auth.ErrorR\x05error\"Y\n" +
	"\x10UserInfoResponse\x12\"\n" +
	"\x04User\x18\x01 \x01(\v2\x0e.auth.UserInfoR\x04User\x12!\n" +
	"\x05Error\x18\x02 \x01(\v2\v.auth.ErrorR\x05Error2\xb2\x02\n" +
	"\vAuthService\x12?\n" +
	"\n" +
	"Introspect\x12\x17.auth.IntrospectRequest\x1a\x18.auth.IntrospectResponse\x12;\n" +
	"\x0eGetLinkedUsers\x12\x0e.auth.LinkedID\x1a\x19.auth.LinkedUsersResponse\x127\n" +
	"\x0fGetMentorGroups\x12\x0e.auth.MentorID\x1a\x14.auth.GroupsResponse\x123\n" +
	"\vGetUserByID\x12\f.auth.UserID\x1a\x16.auth.UserInfoResponse\x127\n" +
	"\x11GetGroupTitleByID\x12\r.auth.GroupID\x1a\x13.auth.GroupResponseB\x14Z\x12api/grpc/v1;authv1b\x06proto3"

var (
	file_api_grpc_v1_auth_proto_rawDescOnce sync.Once
	file_api_grpc_v1_auth_proto_rawDescData []byte
)

func file_api_grpc_v1_auth_proto_rawDescGZIP() []byte {
	file_api_grpc_v1_auth_proto_rawDescOnce.Do(func() {
		file_api_grpc_v1_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_grpc_v1_auth_proto_rawDesc), len(file_api_grpc_v1_auth_proto_rawDesc)))
	})
	return file_api_grpc_v1_auth_proto_rawDescData
}

var file_api_grpc_v1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_api_grpc_v1_auth_proto_goTypes = []any{
	(*IntrospectRequest)(nil),   // 0: auth.IntrospectRequest
	(*IntrospectResponse)(nil),  // 1: auth.IntrospectResponse
	(*UserClaims)(nil),          // 2: auth.UserClaims
	(*Error)(nil),               // 3: auth.Error
	(*LinkedID)(nil),            // 4: auth.LinkedID
	(*MentorID)(nil),            // 5: auth.MentorID
	(*UserID)(nil),              // 6: auth.UserID
	(*GroupID)(nil),             // 7: auth.GroupID
	(*LinkedUsersResponse)(nil), // 8: auth.LinkedUsersResponse
	(*UserInfo)(nil),            // 9: auth.UserInfo
	(*Student)(nil),             // 10: auth.Student
	(*Group)(nil),               // 11: auth.Group
	(*GroupResponse)(nil),       // 12: auth.GroupResponse
	(*GroupsResponse)(nil),      // 13: auth.GroupsResponse
	(*UserInfoResponse)(nil),    // 14: auth.UserInfoResponse
	nil,                         // 15: auth.UserInfo.ContactsEntry
}
var file_api_grpc_v1_auth_proto_depIdxs = []int32{
	2,  // 0: auth.IntrospectResponse.claims:type_name -> auth.UserClaims
	3,  // 1: auth.IntrospectResponse.error:type_name -> auth.Error
	9,  // 2: auth.LinkedUsersResponse.Recipient:type_name -> auth.UserInfo
	9,  // 3: auth.LinkedUsersResponse.Student:type_name -> auth.UserInfo
	3,  // 4: auth.LinkedUsersResponse.error:type_name -> auth.Error
	15, // 5: auth.UserInfo.contacts:type_name -> auth.UserInfo.ContactsEntry
	10, // 6: auth.Group.students:type_name -> auth.Student
	11, // 7: auth.GroupResponse.Group:type_name -> auth.Group
	3,  // 8: auth.GroupResponse.Error:type_name -> auth.Error
	11, // 9: auth.GroupsResponse.groups:type_name -> auth.Group
	3,  // 10: auth.GroupsResponse.error:type_name -> auth.Error
	9,  // 11: auth.UserInfoResponse.User:type_name -> auth.UserInfo
	3,  // 12: auth.UserInfoResponse.Error:type_name -> auth.Error
	0,  // 13: auth.AuthService.Introspect:input_type -> auth.IntrospectRequest
	4,  // 14: auth.AuthService.GetLinkedUsers:input_type -> auth.LinkedID
	5,  // 15: auth.AuthService.GetMentorGroups:input_type -> auth.MentorID
	6,  // 16: auth.AuthService.GetUserByID:input_type -> auth.UserID
	7,  // 17: auth.AuthService.GetGroupTitleByID:input_type -> auth.GroupID
	1,  // 18: auth.AuthService.Introspect:output_type -> auth.IntrospectResponse
	8,  // 19: auth.AuthService.GetLinkedUsers:output_type -> auth.LinkedUsersResponse
	13, // 20: auth.AuthService.GetMentorGroups:output_type -> auth.GroupsResponse
	14, // 21: auth.AuthService.GetUserByID:output_type -> auth.UserInfoResponse
	12, // 22: auth.AuthService.GetGroupTitleByID:output_type -> auth.GroupResponse
	18, // [18:23] is the sub-list for method output_type
	13, // [13:18] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_api_grpc_v1_auth_proto_init() }
func file_api_grpc_v1_auth_proto_init() {
	if File_api_grpc_v1_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_grpc_v1_auth_proto_rawDesc), len(file_api_grpc_v1_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_grpc_v1_auth_proto_goTypes,
		DependencyIndexes: file_api_grpc_v1_auth_proto_depIdxs,
		MessageInfos:      file_api_grpc_v1_auth_proto_msgTypes,
	}.Build()
	File_api_grpc_v1_auth_proto = out.File
	file_api_grpc_v1_auth_proto_goTypes = nil
	file_api_grpc_v1_auth_proto_depIdxs = nil
}
