// Code generated by MockGen. DO NOT EDIT.
// Source: auth_client.go

// Package testdata is a generated GoMock package.
package testdata

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	entities "github.com/parta4ok/kvs/notificationhub/internal/entities"
)

// MockAuthClient is a mock of AuthClient interface.
type MockAuthClient struct {
	ctrl     *gomock.Controller
	recorder *MockAuthClientMockRecorder
}

// MockAuthClientMockRecorder is the mock recorder for MockAuthClient.
type MockAuthClientMockRecorder struct {
	mock *MockAuthClient
}

// NewMockAuthClient creates a new mock instance.
func NewMockAuthClient(ctrl *gomock.Controller) *MockAuthClient {
	mock := &MockAuthClient{ctrl: ctrl}
	mock.recorder = &MockAuthClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthClient) EXPECT() *MockAuthClientMockRecorder {
	return m.recorder
}

// GetLinkedUsers mocks base method.
func (m *MockAuthClient) GetLinkedUsers(ctx context.Context, id string) (*entities.LinkedUsers, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLinkedUsers", ctx, id)
	ret0, _ := ret[0].(*entities.LinkedUsers)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLinkedUsers indicates an expected call of GetLinkedUsers.
func (mr *MockAuthClientMockRecorder) GetLinkedUsers(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLinkedUsers", reflect.TypeOf((*MockAuthClient)(nil).GetLinkedUsers), ctx, id)
}
