name: CI Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: Validate Pull Request
    runs-on: ubuntu-latest

    env:
      TEST_PG_CONN: postgresql://postgres:password@localhost:5432/knowledge?sslmode=disable

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Install Task
        run: |
          sh -c "$(curl -sSL https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin

      - name: Install docker-compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Install migrate
        run: |
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.17.1/migrate.linux-amd64.tar.gz | tar xvz
          sudo mv migrate /usr/local/bin/

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.3.0

      - name: Run unit tests
        run: go test -v ./...

      - name: Run L1 tests
        run: task l1_test

      - name: Run L2 tests
        run: task l2_test
