name: CI Pipeline

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  ci:
    name: Validate Pull Request
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Install Task
        run: |
          sh -c "$(curl -sSL https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin

      - name: Show current dir and ls
        run: |
          pwd
          ls -l

      - name: Run golangci-lint (recommended way)
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.3.0

      - name: Run unit tests
        run: go test -v ./...
#       - name: Run L1 tests
#         run: task l1_test

#       - name: Run L2 tests
#         run: task l2_test
